spring:
  sql:
    init:
      mode: always
  jpa:
#    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

application-settings:
  snippet-size: 160
  user-agent: HelicopterSearchBot
  #  referer:
  ignore-robot-rules: false
  update: false
  tasks-per-site: 1
  connection-interval: 1000
